"""Long/cash moving-average crossover and buy-and-hold, with an explicit ledger.

Timing convention (see docs/architecture.md, "Backtest conventions"):

* Signal on day t uses closes up to and including day t:
  signal[t] = 1 if SMA_short(close[..t]) > SMA_long(close[..t]) else 0.
* The order generated by signal[t] executes at the OPEN of day t+1. The price
  that produced the signal (close[t]) is never the execution price.
* The portfolio is marked to market at every close: equity = cash + shares*close.
* Buys pay  exec = open * (1 + slippage) and fee = fee_rate * shares * exec.
  Sells get exec = open * (1 - slippage) and pay fee = fee_rate * shares * exec.
* Evaluation window [start, end]: the first evaluated day d0 executes the signal
  from the bar before d0, so the long window must be fully warmed up using bars
  strictly before `start`. Bars after `end` are never read.
* Buy-and-hold buys at the open of d0 with the same costs and share rule and is
  never sold. Both strategies start with the same cash at the open of d0.
* An open position at the end is marked at the final close; no exit trade or
  exit cost is simulated for either strategy.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from datetime import date

import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

from quantlab.engine.data import Bars, to_iso

MIN_EVAL_DAYS = 20
MAX_WINDOW = 400


class BacktestInputError(ValueError):
    """Invalid configuration or data. Retrying will not help."""


@dataclass(frozen=True)
class StrategyParams:
    short_window: int
    long_window: int
    initial_capital: float
    fee_bps: float = 0.0
    slippage_bps: float = 0.0
    allow_fractional: bool = True

    def validate(self) -> None:
        if not (1 <= self.short_window < self.long_window <= MAX_WINDOW):
            raise BacktestInputError(
                f"Windows must satisfy 1 <= short < long <= {MAX_WINDOW}; "
                f"got short={self.short_window}, long={self.long_window}."
            )
        if not (math.isfinite(self.initial_capital) and self.initial_capital > 0):
            raise BacktestInputError("Initial capital must be a positive number.")
        for name in ("fee_bps", "slippage_bps"):
            v = getattr(self, name)
            if not (math.isfinite(v) and 0 <= v <= 500):
                raise BacktestInputError(f"{name} must be between 0 and 500 basis points.")


@dataclass
class TradeRecord:
    seq: int
    signal_date: str
    trade_date: str
    side: str
    open_price: float
    exec_price: float
    shares: float
    notional: float
    fee: float
    slippage_cost: float
    cash_after: float


@dataclass
class LedgerResult:
    equity: np.ndarray  # value at each evaluated close
    position: np.ndarray  # shares held at each evaluated close
    trades: list[TradeRecord] = field(default_factory=list)
    total_fees: float = 0.0
    total_slippage: float = 0.0


@dataclass
class BacktestOutput:
    dates: list[str]
    strategy: LedgerResult
    benchmark: LedgerResult
    signal: np.ndarray  # signal at each evaluated close (drives the next open)
    short_ma: np.ndarray
    long_ma: np.ndarray
    notes: list[str]


@dataclass(frozen=True)
class Window:
    start_idx: int
    end_idx: int


def resolve_window(
    bars: Bars, start: date, end: date, long_window: int, min_days: int = MIN_EVAL_DAYS
) -> Window:
    """Map calendar dates to bar indexes and check warm-up and length."""
    if start >= end:
        raise BacktestInputError("Start date must be before end date.")
    s = int(np.searchsorted(bars.dates, np.datetime64(start, "D"), side="left"))
    e = int(np.searchsorted(bars.dates, np.datetime64(end, "D"), side="right")) - 1
    if s >= len(bars) or e < 0 or e < s:
        raise BacktestInputError("No trading days in the selected date range.")
    n = e - s + 1
    if n < min_days:
        raise BacktestInputError(
            f"Only {n} trading days between {start} and {end}; need at least {min_days}."
        )
    # Signal for the bar before d0 needs `long_window` closes ending at index s-1.
    if s < long_window:
        earliest = bars.date_at(long_window) if long_window < len(bars) else None
        hint = f" Earliest valid start is {earliest}." if earliest else ""
        raise BacktestInputError(
            f"Not enough history before {bars.date_at(s)} to warm up a {long_window}-day "
            f"moving average ({s} prior bars available, {long_window} needed).{hint}"
        )
    return Window(s, e)


def earliest_start(bars: Bars, long_window: int) -> date | None:
    return bars.date_at(long_window) if long_window < len(bars) else None


def moving_average(values: np.ndarray, window: int) -> np.ndarray:
    """Trailing simple moving average; NaN until `window` values exist."""
    out = np.full(len(values), np.nan)
    if len(values) >= window:
        out[window - 1 :] = sliding_window_view(values, window).mean(axis=1)
    return out


def crossover_signal(close: np.ndarray, short_window: int, long_window: int):
    short_ma = moving_average(close, short_window)
    long_ma = moving_average(close, long_window)
    valid = ~np.isnan(long_ma)
    signal = np.zeros(len(close), dtype=np.int8)
    signal[valid] = (short_ma[valid] > long_ma[valid]).astype(np.int8)
    return signal, short_ma, long_ma


class _Ledger:
    def __init__(self, cash: float, fee_rate: float, slip_rate: float, fractional: bool):
        self.cash = cash
        self.shares = 0.0
        self.fee_rate = fee_rate
        self.slip_rate = slip_rate
        self.fractional = fractional
        self.trades: list[TradeRecord] = []
        self.total_fees = 0.0
        self.total_slippage = 0.0

    def buy_all(self, open_price: float, trade_date: str, signal_date: str) -> bool:
        exec_price = open_price * (1.0 + self.slip_rate)
        cost_per_share = exec_price * (1.0 + self.fee_rate)
        shares = self.cash / cost_per_share
        if not self.fractional:
            shares = math.floor(shares + 1e-9)
        if shares <= 0:
            return False
        notional = shares * exec_price
        fee = notional * self.fee_rate
        # Clamp tiny negative residue from floating point when spending all cash.
        self.cash = max(self.cash - notional - fee, 0.0)
        self.shares = shares
        self._record("buy", open_price, exec_price, shares, notional, fee, trade_date, signal_date)
        return True

    def sell_all(self, open_price: float, trade_date: str, signal_date: str) -> None:
        exec_price = open_price * (1.0 - self.slip_rate)
        shares = self.shares
        notional = shares * exec_price
        fee = notional * self.fee_rate
        self.cash += notional - fee
        self.shares = 0.0
        self._record("sell", open_price, exec_price, shares, notional, fee, trade_date, signal_date)

    def _record(self, side, open_price, exec_price, shares, notional, fee, trade_date, signal_date):
        slippage = abs(exec_price - open_price) * shares
        self.total_fees += fee
        self.total_slippage += slippage
        self.trades.append(
            TradeRecord(
                seq=len(self.trades) + 1,
                signal_date=signal_date,
                trade_date=trade_date,
                side=side,
                open_price=open_price,
                exec_price=exec_price,
                shares=shares,
                notional=notional,
                fee=fee,
                slippage_cost=slippage,
                cash_after=self.cash,
            )
        )


def run_backtest(
    bars: Bars, params: StrategyParams, start: date, end: date, min_days: int = MIN_EVAL_DAYS
) -> BacktestOutput:
    params.validate()
    win = resolve_window(bars, start, end, params.long_window, min_days)
    s, e = win.start_idx, win.end_idx

    # Only bars up to `end` are visible to the signal: no future data can leak in.
    close_visible = bars.close[: e + 1]
    signal, short_ma, long_ma = crossover_signal(
        close_visible, params.short_window, params.long_window
    )

    fee_rate = params.fee_bps / 10_000.0
    slip_rate = params.slippage_bps / 10_000.0
    strat = _Ledger(params.initial_capital, fee_rate, slip_rate, params.allow_fractional)
    bench = _Ledger(params.initial_capital, fee_rate, slip_rate, params.allow_fractional)
    notes: list[str] = []

    n = e - s + 1
    strat_equity = np.empty(n)
    strat_pos = np.empty(n)
    bench_equity = np.empty(n)
    bench_pos = np.empty(n)
    dates = [to_iso(bars.dates[i]) for i in range(s, e + 1)]
    unaffordable = 0

    for k, t in enumerate(range(s, e + 1)):
        today = dates[k]
        signal_day = to_iso(bars.dates[t - 1])
        open_t = float(bars.open[t])
        target_long = signal[t - 1] == 1

        if k == 0 and not bench.buy_all(open_t, today, signal_day):
            raise BacktestInputError(
                "Initial capital cannot buy one whole share at the first open; "
                "increase capital or allow fractional shares."
            )

        if target_long and strat.shares == 0:
            if not strat.buy_all(open_t, today, signal_day):
                unaffordable += 1
        elif not target_long and strat.shares > 0:
            strat.sell_all(open_t, today, signal_day)

        close_t = float(bars.close[t])
        strat_equity[k] = strat.cash + strat.shares * close_t
        strat_pos[k] = strat.shares
        bench_equity[k] = bench.cash + bench.shares * close_t
        bench_pos[k] = bench.shares

    if unaffordable:
        notes.append(
            f"{unaffordable} buy signal(s) skipped because cash could not buy one whole share."
        )
    if strat.shares > 0:
        notes.append(
            "Strategy ends invested; the final position is marked at the last close "
            "without simulated exit costs."
        )
    notes.append("Buy-and-hold is marked at the last close without simulated exit costs.")

    return BacktestOutput(
        dates=dates,
        strategy=LedgerResult(
            strat_equity, strat_pos, strat.trades, strat.total_fees, strat.total_slippage
        ),
        benchmark=LedgerResult(
            bench_equity, bench_pos, bench.trades, bench.total_fees, bench.total_slippage
        ),
        signal=signal[s : e + 1].copy(),
        short_ma=short_ma[s : e + 1].copy(),
        long_ma=long_ma[s : e + 1].copy(),
        notes=notes,
    )
