"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-02 11:16:40.123666

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pg_trgm backs the GIN index used by the dashboard's experiment-name search.
    # It is a trusted extension, so the database owner can create it (also on RDS).
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "datasets",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("adjustment", sa.String(length=20), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "adjustment IN ('adjusted', 'split_adjusted', 'unadjusted', 'synthetic')",
            name="ck_datasets_adjustment",
        ),
        sa.CheckConstraint("char_length(content_sha256) = 64", name="ck_datasets_sha_len"),
        sa.CheckConstraint("row_count > 0", name="ck_datasets_row_count"),
        sa.CheckConstraint("start_date <= end_date", name="ck_datasets_dates"),
        sa.CheckConstraint("version >= 1", name="ck_datasets_version"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_sha256"),
        sa.UniqueConstraint("name", "version", name="uq_datasets_name_version"),
    )
    op.create_table(
        "sentiment_batches",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'completed', 'failed')",
            name="ck_sentiment_batches_status",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_sentiment_batches_created_at", "sentiment_batches", ["created_at"], unique=False
    )
    op.create_table(
        "strategy_configs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("strategy", sa.String(length=32), nullable=False),
        sa.Column("short_window", sa.Integer(), nullable=False),
        sa.Column("long_window", sa.Integer(), nullable=False),
        sa.Column("fee_bps", sa.Float(), nullable=False),
        sa.Column("slippage_bps", sa.Float(), nullable=False),
        sa.Column("allow_fractional", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("strategy = 'ma_crossover'", name="ck_strategy_configs_strategy"),
        sa.CheckConstraint("fee_bps >= 0 AND fee_bps <= 500", name="ck_strategy_configs_fee"),
        sa.CheckConstraint(
            "short_window >= 1 AND short_window < long_window AND long_window <= 400",
            name="ck_strategy_configs_windows",
        ),
        sa.CheckConstraint(
            "slippage_bps >= 0 AND slippage_bps <= 500", name="ck_strategy_configs_slippage"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "strategy",
            "short_window",
            "long_window",
            "fee_bps",
            "slippage_bps",
            "allow_fractional",
            name="uq_strategy_configs_params",
        ),
    )
    op.create_table(
        "workers",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("hostname", sa.Text(), nullable=False),
        sa.Column("pid", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("current_job_id", sa.BigInteger(), nullable=True),
        sa.Column("sentiment_model_status", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "headlines",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("batch_id", sa.BigInteger(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=300), nullable=False),
        sa.Column("source", sa.String(length=8), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("source IN ('sample', 'user')", name="ck_headlines_source"),
        sa.CheckConstraint("char_length(text) BETWEEN 1 AND 300", name="ck_headlines_text_len"),
        sa.ForeignKeyConstraint(["batch_id"], ["sentiment_batches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_id", "position", name="uq_headlines_batch_position"),
    )
    op.create_table(
        "price_bars",
        sa.Column("dataset_id", sa.BigInteger(), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.CheckConstraint(
            "high >= low AND high >= open AND high >= close AND low <= open AND low <= close",
            name="ck_price_bars_ohlc",
        ),
        sa.CheckConstraint(
            "open > 0 AND high > 0 AND low > 0 AND close > 0", name="ck_price_bars_positive"
        ),
        sa.CheckConstraint("volume IS NULL OR volume >= 0", name="ck_price_bars_volume"),
        sa.ForeignKeyConstraint(["dataset_id"], ["datasets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("dataset_id", "trade_date"),
    )
    op.create_table(
        "workflow_runs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("dataset_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("dev_start", sa.Date(), nullable=False),
        sa.Column("dev_end", sa.Date(), nullable=False),
        sa.Column("holdout_start", sa.Date(), nullable=False),
        sa.Column("holdout_end", sa.Date(), nullable=False),
        sa.Column("initial_capital", sa.Float(), nullable=False),
        sa.Column("fee_bps", sa.Float(), nullable=False),
        sa.Column("slippage_bps", sa.Float(), nullable=False),
        sa.Column("allow_fractional", sa.Boolean(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("variant_keys", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("selection_criterion", sa.Text(), nullable=False),
        sa.Column("selected_strategy_config_id", sa.BigInteger(), nullable=True),
        sa.Column("deterministic_summary", sa.Text(), nullable=True),
        sa.Column("llm_explanation", sa.Text(), nullable=True),
        sa.Column("llm_model", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'completed', 'failed')", name="ck_workflow_runs_status"
        ),
        sa.CheckConstraint(
            "dev_start < dev_end AND dev_end < holdout_start AND holdout_start < holdout_end",
            name="ck_workflow_runs_split",
        ),
        sa.CheckConstraint("initial_capital > 0", name="ck_workflow_runs_capital"),
        sa.ForeignKeyConstraint(["dataset_id"], ["datasets.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["selected_strategy_config_id"], ["strategy_configs.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_workflow_runs_created_at", "workflow_runs", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_workflow_runs_dataset_id"), "workflow_runs", ["dataset_id"], unique=False
    )
    op.create_table(
        "experiments",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("dataset_id", sa.BigInteger(), nullable=False),
        sa.Column("strategy_config_id", sa.BigInteger(), nullable=False),
        sa.Column("dataset_sha256", sa.String(length=64), nullable=False),
        sa.Column("engine_version", sa.String(length=20), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("initial_capital", sa.Float(), nullable=False),
        sa.Column("risk_free_rate", sa.Float(), nullable=False),
        sa.Column("bootstrap_block_length", sa.Integer(), nullable=False),
        sa.Column("bootstrap_resamples", sa.Integer(), nullable=False),
        sa.Column("confidence_level", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("workflow_run_id", sa.BigInteger(), nullable=True),
        sa.Column("rerun_of_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(role = 'standalone') = (workflow_run_id IS NULL)", name="ck_experiments_role_wf"
        ),
        sa.CheckConstraint(
            "role IN ('standalone', 'development', 'holdout')", name="ck_experiments_role"
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'completed', 'failed')", name="ck_experiments_status"
        ),
        sa.CheckConstraint(
            "bootstrap_block_length >= 1 AND bootstrap_resamples BETWEEN 100 AND 20000 AND confidence_level > 0 AND confidence_level < 1",
            name="ck_experiments_bootstrap",
        ),
        sa.CheckConstraint("initial_capital > 0", name="ck_experiments_capital"),
        sa.CheckConstraint("start_date < end_date", name="ck_experiments_dates"),
        sa.ForeignKeyConstraint(["dataset_id"], ["datasets.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["rerun_of_id"], ["experiments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["strategy_config_id"], ["strategy_configs.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["workflow_run_id"], ["workflow_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_experiments_created_at", "experiments", ["created_at"], unique=False)
    op.create_index(op.f("ix_experiments_dataset_id"), "experiments", ["dataset_id"], unique=False)
    op.create_index(
        "ix_experiments_name_trgm",
        "experiments",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_experiments_status_created", "experiments", ["status", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_experiments_workflow_run_id"), "experiments", ["workflow_run_id"], unique=False
    )
    op.create_index(
        "uq_experiments_wf_dev_config",
        "experiments",
        ["workflow_run_id", "strategy_config_id"],
        unique=True,
        postgresql_where=sa.text("role = 'development'"),
    )
    op.create_index(
        "uq_experiments_wf_holdout",
        "experiments",
        ["workflow_run_id"],
        unique=True,
        postgresql_where=sa.text("role = 'holdout'"),
    )
    op.create_table(
        "sentiment_results",
        sa.Column("headline_id", sa.BigInteger(), nullable=False),
        sa.Column("label", sa.String(length=8), nullable=False),
        sa.Column("score_positive", sa.Float(), nullable=False),
        sa.Column("score_negative", sa.Float(), nullable=False),
        sa.Column("score_neutral", sa.Float(), nullable=False),
        sa.Column("model_name", sa.Text(), nullable=False),
        sa.Column("model_revision", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "label IN ('positive', 'negative', 'neutral')", name="ck_sentiment_results_label"
        ),
        sa.CheckConstraint(
            "score_positive BETWEEN 0 AND 1 AND score_negative BETWEEN 0 AND 1 AND score_neutral BETWEEN 0 AND 1",
            name="ck_sentiment_results_scores",
        ),
        sa.ForeignKeyConstraint(["headline_id"], ["headlines.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("headline_id"),
    )
    op.create_table(
        "workflow_events",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("workflow_run_id", sa.BigInteger(), nullable=False),
        sa.Column("node", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('started', 'completed', 'retrying', 'failed', 'resumed', 'info')",
            name="ck_workflow_events_status",
        ),
        sa.ForeignKeyConstraint(["workflow_run_id"], ["workflow_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_workflow_events_run_id", "workflow_events", ["workflow_run_id", "id"], unique=False
    )
    op.create_table(
        "experiment_results",
        sa.Column("experiment_id", sa.BigInteger(), nullable=False),
        sa.Column("eval_start", sa.Date(), nullable=False),
        sa.Column("eval_end", sa.Date(), nullable=False),
        sa.Column("n_days", sa.Integer(), nullable=False),
        sa.Column("strategy_metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("benchmark_metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence_intervals", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("equity_curve", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("notes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("artifact_key", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["experiment_id"], ["experiments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("experiment_id"),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("experiment_id", sa.BigInteger(), nullable=True),
        sa.Column("workflow_run_id", sa.BigInteger(), nullable=True),
        sa.Column("sentiment_batch_id", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column(
            "run_after", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("lease_owner", sa.Text(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(kind = 'backtest' AND experiment_id IS NOT NULL AND workflow_run_id IS NULL AND sentiment_batch_id IS NULL) OR (kind = 'workflow' AND workflow_run_id IS NOT NULL AND experiment_id IS NULL AND sentiment_batch_id IS NULL) OR (kind = 'sentiment' AND sentiment_batch_id IS NOT NULL AND experiment_id IS NULL AND workflow_run_id IS NULL)",
            name="ck_jobs_target",
        ),
        sa.CheckConstraint(
            "status <> 'running' OR (lease_owner IS NOT NULL AND lease_expires_at IS NOT NULL)",
            name="ck_jobs_running_lease",
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'completed', 'failed')", name="ck_jobs_status"
        ),
        sa.CheckConstraint("attempts >= 0 AND attempts <= max_attempts", name="ck_jobs_attempts"),
        sa.CheckConstraint("max_attempts BETWEEN 1 AND 10", name="ck_jobs_max_attempts"),
        sa.ForeignKeyConstraint(["experiment_id"], ["experiments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["sentiment_batch_id"], ["sentiment_batches.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["workflow_run_id"], ["workflow_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_jobs_claimable",
        "jobs",
        ["run_after", "id"],
        unique=False,
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.create_index(
        "ix_jobs_running_lease",
        "jobs",
        ["lease_expires_at"],
        unique=False,
        postgresql_where=sa.text("status = 'running'"),
    )
    op.create_index(
        "uq_jobs_active_experiment",
        "jobs",
        ["experiment_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.create_index(
        "uq_jobs_active_sentiment",
        "jobs",
        ["sentiment_batch_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.create_index(
        "uq_jobs_active_workflow",
        "jobs",
        ["workflow_run_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.create_table(
        "trades",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("experiment_id", sa.BigInteger(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("signal_date", sa.Date(), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("open_price", sa.Float(), nullable=False),
        sa.Column("exec_price", sa.Float(), nullable=False),
        sa.Column("shares", sa.Float(), nullable=False),
        sa.Column("notional", sa.Float(), nullable=False),
        sa.Column("fee", sa.Float(), nullable=False),
        sa.Column("slippage_cost", sa.Float(), nullable=False),
        sa.Column("cash_after", sa.Float(), nullable=False),
        sa.CheckConstraint("side IN ('buy', 'sell')", name="ck_trades_side"),
        sa.CheckConstraint("shares > 0 AND exec_price > 0", name="ck_trades_positive"),
        sa.CheckConstraint("signal_date < trade_date", name="ck_trades_no_lookahead"),
        sa.ForeignKeyConstraint(["experiment_id"], ["experiments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("experiment_id", "seq", name="uq_trades_experiment_seq"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trades")
    op.drop_index(
        "uq_jobs_active_workflow",
        table_name="jobs",
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.drop_index(
        "uq_jobs_active_sentiment",
        table_name="jobs",
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.drop_index(
        "uq_jobs_active_experiment",
        table_name="jobs",
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.drop_index(
        "ix_jobs_running_lease", table_name="jobs", postgresql_where=sa.text("status = 'running'")
    )
    op.drop_index(
        "ix_jobs_claimable", table_name="jobs", postgresql_where=sa.text("status = 'queued'")
    )
    op.drop_table("jobs")
    op.drop_table("experiment_results")
    op.drop_index("ix_workflow_events_run_id", table_name="workflow_events")
    op.drop_table("workflow_events")
    op.drop_table("sentiment_results")
    op.drop_index(
        "uq_experiments_wf_holdout",
        table_name="experiments",
        postgresql_where=sa.text("role = 'holdout'"),
    )
    op.drop_index(
        "uq_experiments_wf_dev_config",
        table_name="experiments",
        postgresql_where=sa.text("role = 'development'"),
    )
    op.drop_index(op.f("ix_experiments_workflow_run_id"), table_name="experiments")
    op.drop_index("ix_experiments_status_created", table_name="experiments")
    op.drop_index(
        "ix_experiments_name_trgm",
        table_name="experiments",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_experiments_dataset_id"), table_name="experiments")
    op.drop_index("ix_experiments_created_at", table_name="experiments")
    op.drop_table("experiments")
    op.drop_index(op.f("ix_workflow_runs_dataset_id"), table_name="workflow_runs")
    op.drop_index("ix_workflow_runs_created_at", table_name="workflow_runs")
    op.drop_table("workflow_runs")
    op.drop_table("price_bars")
    op.drop_table("headlines")
    op.drop_table("workers")
    op.drop_table("strategy_configs")
    op.drop_index("ix_sentiment_batches_created_at", table_name="sentiment_batches")
    op.drop_table("sentiment_batches")
    op.drop_table("datasets")
    # ### end Alembic commands ###
